#!/usr/bin/env bash

if ! type "wget" > /dev/null; then
sudo apt install wget
else
echo ""
fi
if ! type "zenity" > /dev/null; then
sudo apt install zenity
else
echo ""
fi
sudo dpkg --add-architecture i386
wget -nc https://dl.winehq.org/wine-builds/winehq.key && sudo mv winehq.key /usr/share/keyrings/winehq-archive.key
sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
distroVersion=$(lsb_release -r | awk '{print $2}')
if [[ $distroVersion == 20.04 ]]; then
wget -nc https://dl.winehq.org/wine-builds/ubuntu/dists/focal/winehq-focal.sources && sudo mv winehq-focal.sources /etc/apt/sources.list.d/
elif [[ $distroVersion == 21.10 ]]; then
wget -nc https://dl.winehq.org/wine-builds/ubuntu/dists/impish/winehq-impish.sources && sudo mv winehq-impish.sources /etc/apt/sources.list.d/
elif [[ $distroVersion == 21.04 ]]; then
echo 'deb https://dl.winehq.org/wine-builds/ubuntu/ hirsute main' | sudo tee -a /etc/apt/sources.list > /dev/null
elif [[ $distroVersion == 20.10 ]]; then
echo 'deb https://dl.winehq.org/wine-builds/ubuntu/ groovy main' | sudo tee -a /etc/apt/sources.list > /dev/null
elif [[ $distroVersion == 22.04 ]]; then
wget -nc https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources && sudo mv winehq-jammy.sources /etc/apt/sources.list.d/
elif [[ $distroVersion == 18.04 || $distroVersion == 19 || $distroVersion == 19.1 || $distroVersion == 19.2 || $distroVersion == 19.3 ]]; then
wget -nc https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/winehq-bionic.sources && sudo mv winehq-bionic.sources /etc/apt/sources.list.d/
fi
sudo apt update
sudo apt install --install-recommends winehq-staging
sudo apt install winetricks
zenity --warning --text='<span font="20" foreground="black">Select Windows Version as Windows 7 in opening window</span>' --title="Alert"
winecfg
winetricks -q dxvk
wget https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B885CD177-3BB6-C201-A889-B01A263811E4%7D%26lang%3Den%26browser%3D4%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-stable-statsdef_1%26installdataindex%3Dempty/update2/installers/ChromeSetup.exe
wine ChromeSetup.exe
sed -i '3s/$/ --no-sandbox/' ~/.local/share/applications/wine/Programs/Google\ Chrome.desktop
if [ ! -d "~/Desktop/" ]; then
    sed -i '3s/$/ --no-sandbox/' ~/Masaüstü/Google\ Chrome.desktop
elif [ ! -d "~/Masaüstü/" ]; then
    sed -i '3s/$/ --no-sandbox/' ~/Desktop/Google\ Chrome.desktop
fi
